### ISSUE TITLE
Increase PHP version

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/wp-cli-bundle#330]
https://github.com/wp-cli/wp-cli-bundle/blob/398a1d8f618bfa5c4b1eb8300004153ff3efa267/composer.json#L47-L50

Set the PHP version to at least PHP 7.2.

I get that WP has support that goes back to PHP 5.6, however I am certain that people apt enough to use wp cli will not be on a version that old, that has potential security issues.

The reason why wp-cli should upgrade, since there are some bugs in tools used by wp-cli (e.g. gettext) that have been fixed in newer versions of these tools - which however require at least PHP 7.2.

**Comment by schlessera** [comment]
Thanks for raising the issue, @kkmuffme !

WP-CLI has an established for managing its PHP version requirements, which you can read here: https://make.wordpress.org/cli/2019/01/15/wp-cli-php-requirements-strategy/

Usage of WP-CLI is not bound to the skill level of its users (which in turn says nothing about the types of environments they need to manage). Given that WP-CLI is the infrastructure backbone of many of the systems that are supposed to be porting WordPress installations over from PHP 5.6 to something more recent once WP Core has raised its minimum, WP-CLI will always need to trail behind the PHP version support of WordPress, instead of leading it.
