### ISSUE TITLE
Automatically submit pull requests for 'wp-cli/wp-cli' updates

### ISSUE THREAD

**Issue by danielbachhuber** [wp-cli/wp-cli-bundle#468]
Given so much of our development workflow is automated, it's easy to forget to submit updates like https://github.com/wp-cli/wp-cli-bundle/pull/467

Ideally, Dependabot (or something similar) would update the `wp-cli/wp-cli` dependency and automatically submit these pull request for us.

**Done is:**
* `wp-cli/wp-cli` dependency updates are submitted with some automated system.

**Comment by eiriksm** [comment]
Hey there.

Just randomly stumbled across this while doing some marketing research.🤓

Violinist.io can easily (and quickly) do that. Totally free, for life ✌️

More PHP specific than dependabot, and of course in my very subjective opinion, also better.

Sorry if this came off spammy, I won't spam any more though. Let me know if you want more information or help setting it up, otherwise I will not comment on this issue again ✌️

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @eiriksm ! I'm not sure we want to add another tool to our toolkit right now, though.

**Comment by eiriksm** [comment]
Makes sense 👍

Let me know if I can help. And know that violinist is great at keeping dependencies that are on dev releases (just a branch with commits) up to date. Ok that's it for marketing, thanks for answering and keep on being great and open source ❤️✌️

**Comment by danielbachhuber** [comment]
Add a workflow to keep `wp-cli/wp-cli` up to date: https://github.com/wp-cli/wp-cli-bundle/blob/main/.github/workflows/update-framework.yml
